[package]
name = "rtrack"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.3"
pallet = "0.7.0"
serde = "1.0.130"
sled = "0.34.7"
tantivy = "0.16.1"
chrono = "0.4"